# Generated by Django 5.2.14 on 2026-06-01 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('device_code', models.CharField(max_length=40, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintenance', '维护中')], default='online', max_length=20)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['device_code'],
            },
        ),
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('tailgating', '尾随通行'), ('forced_open', '暴力开门'), ('device_offline', '设备离线'), ('blacklist', '黑名单告警')], max_length=30)),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('resolved', '已处理')], default='open', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('handled_by', models.CharField(blank=True, max_length=60)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='access.accessdevice')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('host_name', models.CharField(max_length=60)),
                ('reason', models.CharField(max_length=160)),
                ('visit_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('pass_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=20)),
                ('id_card_last4', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitor_passes', to='access.accessdevice')),
            ],
            options={
                'ordering': ['-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='DoorOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opener_name', models.CharField(max_length=60)),
                ('opener_type', models.CharField(choices=[('resident', '业主'), ('visitor', '访客'), ('admin', '管理员'), ('system', '系统')], max_length=20)),
                ('credential_method', models.CharField(choices=[('face', '人脸'), ('card', '门禁卡'), ('qrcode', '二维码'), ('remote', '远程开门'), ('password', '密码')], max_length=20)),
                ('result', models.CharField(choices=[('success', '成功'), ('denied', '拒绝')], default='success', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('failure_reason', models.CharField(blank=True, max_length=160)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='door_logs', to='access.accessdevice')),
                ('visitor_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_logs', to='access.visitorpass')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
